# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a5961d4e0390c775bd914b4182a9e2917239bb4dfb957a81cc8e23c144f8f873715163022269b5fb0ebda3eda7b73244659eccc0b5bcd09992232609135d6551

test:
  secret_key_base: 66fde46770fa2f3a4c463f3196217df6eb47a967f0d8e732439497f99494a55232df29f4fd0df625fea6fa673390a5f9d38b427f1d76b4f11be174e68bc1d2ce

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
